
workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.gradle/caches
    scripts:
      - name: Flutter build
        script: |
          flutter build appbundle --debug
    artifacts:
      - build/app/outputs/bundle/debug/app-debug.aab
